{% set name = "yarl" %}
{% set version = "1.1.1" %}
{% set sha256 = "a69dd7e262cdb265ac7d5e929d55f2f3d07baaadd158c8f19caebf8dde08dfe8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python
    - multidict >=4.0
    - idna >=2.0

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test tests

about:
  home: https://github.com/aio-libs/yarl
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Yet another URL library'

  doc_url: http://yarl.readthedocs.io/
  dev_url: https://github.com/aio-libs/yarl

extra:
  recipe-maintainers:
    - sodre
