{% set name = "yarl" %}
{% set version = "1.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ac374123c6fd7abf64d1fec93962b0bd4ee2c19751755a762a72dd96c0378f8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - expandvars
    - setuptools >=82.0.1
    - wheel
    - tomli  # [py<311]
    - pip
    # See https://github.com/aio-libs/yarl/blob/v{{ version }}/requirements/cython.txt
    - cython 3.2.4
  run:
    - python
    - idna >=2.0
    - multidict >=4.0
    - propcache >=0.2.1

test:
  imports:
    - yarl
  source_files:
    - tests
  commands:
    - pip check
    - pytest -n auto -v tests
  requires:
    - hypothesis
    - pip
    - pytest ==9.0.3
    - pytest-xdist

about:
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  description: The module provides handy URL class for URL parsing and changing.
  doc_url: https://yarl.aio-libs.org
  dev_url: https://github.com/aio-libs/yarl

extra:
  recipe-maintainers:
    - sodre
  skip-lints:
    - host_section_needs_exact_pinnings
