{% set name = "yarl" %}
{% set version = "1.11.0" %}
{% set sha256 = "f86f4f4a57a29ef08fa70c4667d04c5e3ba513500da95586208b285437cb9592" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<=37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - expandvars
    - setuptools
    - wheel
    - tomli  # [py<311]
    - pip
    - cython 3.0
  run:
    - python
    - multidict >=4.0
    - idna >=2.0
    - typing-extensions >=3.7.4 # [py<38]

test:
  imports:
    - yarl
  source_files:
    - pytest.ini
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytest-xdist
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  doc_url: https://yarl.aio-libs.org
  dev_url: https://github.com/aio-libs/yarl

extra:
  recipe-maintainers:
    - sodre
