{% set name = "yarl" %}
{% set version = "1.1.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a69dd7e262cdb265ac7d5e929d55f2f3d07baaadd158c8f19caebf8dde08dfe8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python
    - multidict >=4.0
    - idna >=2.0

test:
  imports:
    - yarl
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test tests

about:
  home: https://github.com/aio-libs/yarl
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  doc_url: http://yarl.readthedocs.io
  dev_url: https://github.com/aio-libs/yarl
  doc_source_url: https://github.com/aio-libs/yarl/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
