{% set name = "yarl" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20d95535e7d833889982bfe7cc321b7f63bf8879788fee982c76ae2b24cfb715

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - expandvars
    - setuptools >=47
    - wheel
    - tomli  # [py<311]
    - pip
    - cython 3.1
  run:
    - python
    - multidict >=4.0
    - idna >=2.0
    - propcache >=0.2.0

test:
  imports:
    - yarl
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-xdist
    - hypothesis
  commands:
    - pip check
    # missing pytest-codspeed for benchmark
    - pytest -n auto -v tests --ignore=tests/test_quoting_benchmarks.py --ignore=tests/test_url_benchmarks.py

about:
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  description: The module provides handy URL class for URL parsing and changing.
  doc_url: https://yarl.aio-libs.org
  dev_url: https://github.com/aio-libs/yarl

extra:
  recipe-maintainers:
    - sodre
