travis:
  secure:
    BINSTAR_TOKEN: cECmx9TT4SvubYdsMVw/cAnZSSfKVBX+gDRwhoK9SqckyTv7l+1GY0uewovYJy0i1Z6DHO7fn8qmD3thv0inI1l1WUSOtYcXAf6d70mi+vGsSpugAJRMGdMrCT1Kaq+Oonpoa1nYZ3epk37ZjA/I8MgtufiNGcH9C8WZDBQjpp+p7RgfGJzyjy4hozLOs4qJg3P6NiXl/vg3Pukngo5sooH1t+f0N/Z3XWDmymGidF7btGNH7+ZQ2wGT/XtjmOErSxS05EZET3jdbh1oi3gfpYBMJ0jkSEKu8qqfPD6/j5flnDeLpLKD3w5NQ2bGX32wATxZ4DHdD/wym/bu+G/DCxGOlhjC71t6JbqvWnky5zwAl9EvcKBCAjwDeiQTmg1FX9WxcNKR5I8GT6Zc3k0+cIQjodd2zY4pkpvkXZosCJMAukq3uYXKzBOdiyuZ/3vb9Vg3RnpbxMMm80tXVOgvcGAmo20OJHWQeFY2rieUOsDdzitYqSrhjl50JzxvxLa/W2sHD8uG641tknG+NTvB/HuSSzN1R73kBGRRKfpm9zur2tpqFnHkJv4G+LYzFa7nDpq/vV4oS0ZrK+DorbCZsCtxHgQVw3Sw23M2jaYXgW5rCP+bpSb8A+0C7l5qIVLi4OLzdI8Xj5KBj4/2YoM+LglIYGauAgHBKc4XLhtDXEI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
