travis:
  secure:
    BINSTAR_TOKEN: kUwaGvexfmFtcse75wKNz9g5B2W5XIzONhPwNNCeWYFlyoq8jSuGg3n7vEjQUvXUtMtkNMLuOA6luzl5aqWsIE5JMvtiTtf1XCbhmXEAG2USYk/7yrpZ3w/CYiustYiqcGJz5F4zCrbMg1wAiIeicAbSqKRvfo6LkfUkOQv9bqoi6sYjnQmZkARFctazXo23Z1HlinqQdM9RySpo89sj6yxeJajVsA4cFUkUQHnxWMcSf4di9zkva7dyCMefN8gimgy5wDbX3aaAeFNsW7R6w4cp3ok7eQfZtEJo0eSxE9BOqMUEDyTjjvDRK1j0HVLVcmpJUKze787ljFM43YmXdkGaoeCg9lvPg8yEOG/5K/oGJ+ksEMQUHnhwqtA9Vy63v8j6UpsFCF6zbP3U6EBQTxvVs4U6wAB0Fc3JOizho5Ms3/3s2jRomvucckKWb5s5MWOY7SfGgvaKpdh07FlI38jvM6kJvtWjbWkjyzSmSYPtx8pktBnTWHewdPbaQwrHQyMf5zf7XXewOMp6BY4BLzsflF3T33D3IdYLh31BlECT9J/QEhk5kXeIxtiqpU79qjK/QvYXlQUBYMAawvw0egGU6BbV9eimSRkW9bvN3p1QG8tb91JYTkhsCSB/Ap8CNvQJB77mmkjtC9oMfyHMq+RmLQhdSXEkUnEuhylcBIU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
